/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProcessorOperationArgumentDesc { 
    name?: string;
    optional?: boolean;
    type?: ProcessorOperationArgumentDesc.TypeEnum;
}
export namespace ProcessorOperationArgumentDesc {
    export type TypeEnum = 'FLOAT' | 'INT' | 'STRING' | 'DATE' | 'FLOAT_LIST' | 'INT_LIST' | 'STRING_LIST' | 'DATE_LIST' | 'VOID';
    export const TypeEnum = {
        FLOAT: 'FLOAT' as TypeEnum,
        INT: 'INT' as TypeEnum,
        STRING: 'STRING' as TypeEnum,
        DATE: 'DATE' as TypeEnum,
        FLOATLIST: 'FLOAT_LIST' as TypeEnum,
        INTLIST: 'INT_LIST' as TypeEnum,
        STRINGLIST: 'STRING_LIST' as TypeEnum,
        DATELIST: 'DATE_LIST' as TypeEnum,
        VOID: 'VOID' as TypeEnum
    };
}
