/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ProcessorOperationArgument } from '../model/processorOperationArgument';
import { ProcessorOperationDesc } from '../model/processorOperationDesc';
import { SignalProcessorDTO } from '../model/signalProcessorDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SignalProcessorResourceService {

    protected basePath = 'https://localhost:8100';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createSignalProcessor
     * 
     * @param signalProcessor signalProcessor
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSignalProcessorUsingPOST(signalProcessor: SignalProcessorDTO, observe?: 'body', reportProgress?: boolean): Observable<SignalProcessorDTO>;
    public createSignalProcessorUsingPOST(signalProcessor: SignalProcessorDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SignalProcessorDTO>>;
    public createSignalProcessorUsingPOST(signalProcessor: SignalProcessorDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SignalProcessorDTO>>;
    public createSignalProcessorUsingPOST(signalProcessor: SignalProcessorDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (signalProcessor === null || signalProcessor === undefined) {
            throw new Error('Required parameter signalProcessor was null or undefined when calling createSignalProcessorUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<SignalProcessorDTO>(`${this.basePath}/api/signal-processors`,
            signalProcessor,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * executeSignalProcessorOperations
     * 
     * @param id id
     * @param name name
     * @param operationArguments operationArguments
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public executeSignalProcessorOperationsUsingPUT(id: number, name: string, operationArguments: Array<ProcessorOperationArgument>, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public executeSignalProcessorOperationsUsingPUT(id: number, name: string, operationArguments: Array<ProcessorOperationArgument>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public executeSignalProcessorOperationsUsingPUT(id: number, name: string, operationArguments: Array<ProcessorOperationArgument>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public executeSignalProcessorOperationsUsingPUT(id: number, name: string, operationArguments: Array<ProcessorOperationArgument>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling executeSignalProcessorOperationsUsingPUT.');
        }

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling executeSignalProcessorOperationsUsingPUT.');
        }

        if (operationArguments === null || operationArguments === undefined) {
            throw new Error('Required parameter operationArguments was null or undefined when calling executeSignalProcessorOperationsUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<string>(`${this.basePath}/api/signal-processors/${encodeURIComponent(String(id))}/operations/${encodeURIComponent(String(name))}`,
            operationArguments,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSignalProcessorOperations
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSignalProcessorOperationsUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ProcessorOperationDesc>>;
    public getSignalProcessorOperationsUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProcessorOperationDesc>>>;
    public getSignalProcessorOperationsUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProcessorOperationDesc>>>;
    public getSignalProcessorOperationsUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSignalProcessorOperationsUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ProcessorOperationDesc>>(`${this.basePath}/api/signal-processors/${encodeURIComponent(String(id))}/operations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSignalProcessor
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSignalProcessorUsingGET1(id: number, observe?: 'body', reportProgress?: boolean): Observable<SignalProcessorDTO>;
    public getSignalProcessorUsingGET1(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SignalProcessorDTO>>;
    public getSignalProcessorUsingGET1(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SignalProcessorDTO>>;
    public getSignalProcessorUsingGET1(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSignalProcessorUsingGET1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SignalProcessorDTO>(`${this.basePath}/api/signal-processors/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSignalProcessors
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSignalProcessorsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<SignalProcessorDTO>>;
    public getSignalProcessorsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SignalProcessorDTO>>>;
    public getSignalProcessorsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SignalProcessorDTO>>>;
    public getSignalProcessorsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SignalProcessorDTO>>(`${this.basePath}/api/signal-processors`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateSignalProcessor
     * 
     * @param space space
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSignalProcessorUsingPUT(space: SignalProcessorDTO, observe?: 'body', reportProgress?: boolean): Observable<SignalProcessorDTO>;
    public updateSignalProcessorUsingPUT(space: SignalProcessorDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SignalProcessorDTO>>;
    public updateSignalProcessorUsingPUT(space: SignalProcessorDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SignalProcessorDTO>>;
    public updateSignalProcessorUsingPUT(space: SignalProcessorDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (space === null || space === undefined) {
            throw new Error('Required parameter space was null or undefined when calling updateSignalProcessorUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<SignalProcessorDTO>(`${this.basePath}/api/signal-processors`,
            space,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
