/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { SpaceDTO } from '../model/spaceDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SpaceResourceService {

    protected basePath = 'https://localhost:8100';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createSpace
     * 
     * @param space space
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSpaceUsingPOST(space: SpaceDTO, observe?: 'body', reportProgress?: boolean): Observable<SpaceDTO>;
    public createSpaceUsingPOST(space: SpaceDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SpaceDTO>>;
    public createSpaceUsingPOST(space: SpaceDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SpaceDTO>>;
    public createSpaceUsingPOST(space: SpaceDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (space === null || space === undefined) {
            throw new Error('Required parameter space was null or undefined when calling createSpaceUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<SpaceDTO>(`${this.basePath}/api/spaces`,
            space,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSpace
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpaceUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<SpaceDTO>;
    public getSpaceUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SpaceDTO>>;
    public getSpaceUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SpaceDTO>>;
    public getSpaceUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSpaceUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SpaceDTO>(`${this.basePath}/api/spaces/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSpacesBelongingToSpace
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpacesBelongingToSpaceUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<Array<SpaceDTO>>;
    public getSpacesBelongingToSpaceUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SpaceDTO>>>;
    public getSpacesBelongingToSpaceUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SpaceDTO>>>;
    public getSpacesBelongingToSpaceUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSpacesBelongingToSpaceUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SpaceDTO>>(`${this.basePath}/api/spaces/${encodeURIComponent(String(id))}/spaces`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSpaces
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpacesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<SpaceDTO>>;
    public getSpacesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SpaceDTO>>>;
    public getSpacesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SpaceDTO>>>;
    public getSpacesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SpaceDTO>>(`${this.basePath}/api/spaces`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateSpace
     * 
     * @param space space
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSpaceUsingPUT(space: SpaceDTO, observe?: 'body', reportProgress?: boolean): Observable<SpaceDTO>;
    public updateSpaceUsingPUT(space: SpaceDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SpaceDTO>>;
    public updateSpaceUsingPUT(space: SpaceDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SpaceDTO>>;
    public updateSpaceUsingPUT(space: SpaceDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (space === null || space === undefined) {
            throw new Error('Required parameter space was null or undefined when calling updateSpaceUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<SpaceDTO>(`${this.basePath}/api/spaces`,
            space,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
